###############
### SOURCES ###
###############

source = ~/dotfiles/hypr/.config/hypr/monitors.conf
source = ~/dotfiles/hypr/.config/hypr/looknfeel.conf
source = ~/dotfiles/hypr/.config/hypr/input.conf
source = ~/dotfiles/hypr/.config/hypr/keybindings.conf
source = ~/dotfiles/hypr/.config/hypr/layerswindowsworkspaces.conf
source = ~/dotfiles/hypr/.config/hypr/envirovariables.conf
source = ~/dotfiles/hypr/.config/hypr/permissions.conf

###################
### MY PROGRAMS ###
###################

$terminal = ghostty
$fileManager = nautilus
#$menu = rofi -show drun
$menu = ~/.config/rofi/launchers/type-4/launcher.sh
$notif = swaync
$codeEditor = code --enable-features=UseOzonePlatform --ozone-platform=wayland 

#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & $notif
exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = iwd & cliphist
#exec-once = pipewire & pipewire-pulse & wireplumber & pipewire-alsa
